jobs:
  - name: tri-manifest
    type: manifest
    steps:
      - GET: tri-redis
      - GET: tri-params

  - name: tri-deploy
    type: tripubDeploy
    steps:
      - GET: tri-manifest
      - GET: tri-cluster
    
