jobs:
  - name: tri-manifest
    type: manifest
    steps:
      - GET: tri-nginx
      - GET: tri-params
      - GET: tri-docker-opts

  - name: tri-deploy
    type: tripubDeploy
    steps:
      - GET: tri-manifest
      - GET: tri-cluster
    
