triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'testing trigger in yml2'
      
  - name: triggertest2
    type: trigger
    source:
      counter: 1
      
  - name: triggertest3
    type: trigger
    source:
      counter: 1
