jobs:
  - name: ecs-man
    type: manifest
    steps:
      - GET: ecs-sn

  - name: ecs-jatin-upgrade-deploy
    type: ecsDeploy
    options:
      deployMethod: upgrade
    steps:
      - GET: ecs-man
      - GET: ecs-cluster
