jobs:
  - name: ecs-man
    type: manifest
    steps:
      - GET: ecs-sn

  - name: ecs-bluegreen-new-deploy
    type: ecsDeploy
    options:
      deployMethod: blueGreen
    steps:
      - GET: ecs-man
      - GET: ecs-cluster
