jobs:
  - name: tri-manifest-1
    type: manifest
    steps:
      - GET: tri-sn
      - GET: tri-params
      - GET: tri-docker-opts
      - GET: triggertest1

  - name: tri-deploy
    type: tripubDeploy
    options:
      deployMethod: blueGreen
    steps:
      - GET: tri-manifest-1
      - GET: tri-cluster
    
