jobs:
  - name: ecs-man
    type: manifest
    steps:
      - GET: ecs-nfinx

  - name: ecs-upgrade-new-deploy
    type: ecsDeploy
    options:
      deployMethod: upgrade
    steps:
      - GET: ecs-man
      - GET: ecs-cluster
